/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'user' at '5/16/19 10:35 PM' with Gradle 3.0
 *
 * @author user, @date 5/16/19 10:35 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
