/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'user' at '4/6/19 5:37 PM' with Gradle 3.0
 *
 * @author user, @date 4/6/19 5:37 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
