angular.module("SwabhavTechLab", ["ui.router"])
    .config(
        function ($stateProvider,$urlRouterProvider) {
        $stateProvider
        .state('home',{
            url:'/home',
            templateUrl:'partial/home.html',
            controller:'HomeController'
        })
        .state('about',{
            url:'/about',
            templateUrl:'partial/about.html',
            controller:'AboutController'
        })
        .state('career',{
            url:'/career',
            templateUrl:'partial/career.html',
            controller:'CareerController'
        })
        .state('career.contact',{
            url:'/contact',
            templateUrl:'partial/contact.html',
            controller:'contactController'
        })
        .state('career.detail',{
            url:'/detail',
            templateUrl:'partial/detail.html',
            controller:'detailController'
        })
        $urlRouterProvider.otherwise('/home')
    })