/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'user' at '5/18/19 11:56 AM' with Gradle 3.0
 *
 * @author user, @date 5/18/19 11:56 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
